name: githab-actions

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: e2b03042-33da-45da-8108-0470f0b01f7a
        continue-on-error: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: make setup
      # Запускаем линтер
      - run: make lint
      # Запускаем тесты
      - run: make tests
